/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Models.Account;
import controller.StaffController;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author qcuon
 */
public class Staff extends javax.swing.JFrame {

    String UserName;
    Account myAccount;
    Account guestAccount;

    /**
     * Creates new form Staff
     */
    public Staff() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void setUserName(String UserNames) {
        this.UserName = UserNames;

    }

    public void loadStaff(String UserName) {
        myAccount = StaffController.loadInfor(UserName);
        guestAccount = myAccount;
        loadAcountToView(myAccount);
    }

    public void loadAcountToView(Account account) {
        tfFullName.setText(account.getFullName());
        tfUserName.setText(account.getUserName());
        tfFindStaff.setText(account.getUserName());
        if (account.getType() == 1) {
            cbPower.setSelectedIndex(1);
        } else {
            cbPower.setSelectedIndex(0);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFindStaff = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbPower = new javax.swing.JComboBox<>();
        btnAddStaff = new javax.swing.JButton();
        btnUpdateStaff = new javax.swing.JButton();
        btnDeleteStaff = new javax.swing.JButton();
        tfFullName = new javax.swing.JTextField();
        tfUserName = new javax.swing.JTextField();
        tfFindStaff = new javax.swing.JTextField();
        PassWordOld = new javax.swing.JPasswordField();
        tfPassWordNew = new javax.swing.JPasswordField();
        tfRepeatPassWord = new javax.swing.JPasswordField();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Thông tin nhân viên");

        btnFindStaff.setText("Tìm kiếm");
        btnFindStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindStaffActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tên nhân viên:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tên đăng nhập:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mật khẩu cũ:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Mật khẩu mới:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nhập lại mật khẩu:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Cấp quyền:");

        cbPower.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Quản lý" }));

        btnAddStaff.setText("Thêm");
        btnAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStaffActionPerformed(evt);
            }
        });

        btnUpdateStaff.setText("Cập nhật");
        btnUpdateStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStaffActionPerformed(evt);
            }
        });

        btnDeleteStaff.setText("Xóa");
        btnDeleteStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStaffActionPerformed(evt);
            }
        });

        tfFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFullNameActionPerformed(evt);
            }
        });

        tfFindStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFindStaffActionPerformed(evt);
            }
        });
        tfFindStaff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfFindStaffKeyPressed(evt);
            }
        });

        tfPassWordNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassWordNewActionPerformed(evt);
            }
        });

        btnRefresh.setText("Làm mới");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnAddStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                        .addComponent(PassWordOld)
                                        .addComponent(tfPassWordNew)
                                        .addComponent(tfRepeatPassWord))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btnUpdateStaff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tfFindStaff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFindStaff)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindStaff)
                    .addComponent(tfFindStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PassWordOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(tfPassWordNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfRepeatPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStaff)
                    .addComponent(btnUpdateStaff)
                    .addComponent(btnDeleteStaff)
                    .addComponent(btnRefresh))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffActionPerformed
        // TODO add your handling code here:
        String userName = tfUserName.getText();
        String fullName = tfFullName.getText();
        String passWord = tfPassWordNew.getText();
        String repeatPassWord = tfRepeatPassWord.getText();
        int type = cbPower.getSelectedIndex();
        if (userName == "" || passWord == "" || repeatPassWord == "") {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ thông tin!!!");
        } else if (StaffController.loadInfor(userName) == null) {
            if (passWord == "") {
                JOptionPane.showMessageDialog(this, "Mật khẩu không hợp lệ!!!");
            }
            else {
                if (passWord.equals(repeatPassWord)) {
                StaffController.AddStaff(fullName, userName, passWord, type);
                } else {
                    JOptionPane.showMessageDialog(this, "Mật khẩu không đồng nhất!!!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Azoo, thằng này có account zồi!!!");
        }
    }//GEN-LAST:event_btnAddStaffActionPerformed

    private void btnUpdateStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStaffActionPerformed
        // TODO add your handling code here:
        String fullName = tfFullName.getText();
        String userName = tfUserName.getText();
        String accountName = tfFindStaff.getText();
        String passWordOld = PassWordOld.getText();
        String passWordNew = tfPassWordNew.getText();
        String repeatPassWord = tfRepeatPassWord.getText();
        int type = cbPower.getSelectedIndex();
        if(fullName.equals(null)||userName.equals(null)){
            JOptionPane.showMessageDialog(this, "Kiểm tra nhập đầy đủ thông tin @_@");
        }
        else{
            if (userName.equals(guestAccount.getUserName())) {
                if (guestAccount.getUserName().equals(myAccount.getUserName())) {
                    if (passWordOld.equals(myAccount.getPassWord())){
                        if (passWordNew.equals(repeatPassWord)) {
                            if (passWordNew.equals("")){
                                StaffController.EditMySelf(fullName, passWordOld,type, myAccount.getUserName());
                            }
                            else StaffController.EditMySelf(fullName, passWordNew,type, myAccount.getUserName());
                        }else JOptionPane.showMessageDialog(this, "Mật khẩu không đồng nhất.");
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Sai mật khẩu cũ rồi *-* \nNhập lại nha!!");
                    }
                }
                else{
                    StaffController.EditStaff(fullName, type,userName);
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "Không được đổi tên đăng nhập!!!");
            }
        }
    }//GEN-LAST:event_btnUpdateStaffActionPerformed

    private void btnDeleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStaffActionPerformed
        // TODO add your handling code here:
        String userName = tfUserName.getText();
        StaffController.DeleteStaff(userName);
    }//GEN-LAST:event_btnDeleteStaffActionPerformed

    private void btnFindStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindStaffActionPerformed
        // TODO add your handling code here:
        findStaff();
    }//GEN-LAST:event_btnFindStaffActionPerformed

    private void tfFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFullNameActionPerformed

    private void tfPassWordNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassWordNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassWordNewActionPerformed

    private void tfFindStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFindStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFindStaffActionPerformed

    private void tfFindStaffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFindStaffKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            findStaff();
        }
    }//GEN-LAST:event_tfFindStaffKeyPressed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadStaff(UserName);
        tfPassWordNew.setEnabled(true);
        tfRepeatPassWord.setEnabled(true);
        PassWordOld.setEnabled(true);
    }//GEN-LAST:event_btnRefreshActionPerformed

    public void setPower(boolean isAdmin) {
        if (!isAdmin) {
            btnFindStaff.setEnabled(false);
            btnAddStaff.setEnabled(false);
            btnDeleteStaff.setEnabled(false);
            cbPower.setEnabled(false);
        }
    }

    public void findStaff(){
        String userName = tfFindStaff.getText();
        int check = StaffController.CheckUserName(userName);
        if (check == 1) {
            guestAccount = StaffController.loadInfor(userName);
            loadAcountToView(guestAccount);
            if(guestAccount.equals(myAccount)){
            
            }else{
                tfPassWordNew.setEnabled(false);
                tfRepeatPassWord.setEnabled(false);
                PassWordOld.setEnabled(false);
            }
            if (guestAccount.getType() == 1) {
                btnDeleteStaff.setEnabled(false);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Bác này không có trong danh sách ^_^");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PassWordOld;
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnDeleteStaff;
    private javax.swing.JButton btnFindStaff;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdateStaff;
    private javax.swing.JComboBox<String> cbPower;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tfFindStaff;
    private javax.swing.JTextField tfFullName;
    private javax.swing.JPasswordField tfPassWordNew;
    private javax.swing.JPasswordField tfRepeatPassWord;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables
}
